### PR TITLE
Update ArrayUtil.js

### PR DESCRIPTION
**Pull request by FreezePhoenix**
Lets just say that this might help a little?

### CODE REVIEW

**Comment by FreezePhoenix** [comment]
@fabiocaccamo This PR adds the `Array.zip` and `Array.unzip` methods you were going to add.

**Comment by fabiocaccamo** [comment]
Hi, 
I appreciate your support but your PR is not ok for the following reasons:
- as you can see, the whole lib is written in es5
- your `ArrayUtil.zip` and `ArrayUtil.unzip` code is not clear, there are a lot of function calls, please check my [implementation](https://github.com/fabiocaccamo/utils.js/blob/master/src/utils/ArrayUtil.js#L176), it's very simple :) 
- your `ObjectUtil.clone` implementation doesn't clone nested objects and arrays.

By the way, I just published this lib and I'm writing tests now, many things could change in the short period...

**Comment by FreezePhoenix** [comment]
Hi,
Thank you for your constructive response,
As you have noticed, `ObjectUtil.clone` does not clone nested objects and arrays. That is called *deep-cloning*. If you were to implement such a method, it would be `ObjectUtil.deepClone` or `ObjecUtils.cloneDeep`.

As for the `ArrayUtil.zip` and `ArrayUtil.unzip` I can fix that.

**Comment by FreezePhoenix** [comment]
@fabiocaccamo  I would like this PR to be reopened. The operations added in this PR are not 'simple' nor is there a 'best' way to do them.

**Pull request closed without merging**
